/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_fudan_ee_cameraview_NativeMethod */

#ifndef _Included_cn_edu_fudan_ee_cameraview_NativeMethod
#define _Included_cn_edu_fudan_ee_cameraview_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_fudan_ee_cameraview_NativeMethod
 * Method:    CountAndSum
 * Signature: ([B[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_edu_fudan_ee_cameraview_NativeMethod_CountAndSum
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
